// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcshqdpqvczadeivxnuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjc2hxZHBxdmN6YWRlaXZ4bnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzUyNzQsImV4cCI6MjA2OTE1MTI3NH0.yi1JyMRqssmUbqyCWkJ8hJkxU2FsWxIP2VqowLqviSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});